// client/packages/vance-face/src/chat/MessageBubble.vue
<script setup lang="ts">
import { computed } from 'vue';
import { MarkdownView } from '@components/index';
import { uiTheme, paletteStyle } from '@composables/useUiTheme';
import QuestionCanvas, { type QuestionOption } from './QuestionCanvas.vue';

// Action-type values mirror constants in
// {@code ChatMessageDocument.ACTION_TYPE_*}.
const ACTION_TYPE_ASK_USER = 'ASK_USER';
const ACTION_TYPE_REJECT = 'REJECT';
const ACTION_TYPE_WAIT = 'WAIT';

// Role on the wire is the Java enum *name* (`"USER"` / `"ASSISTANT"` /
// `"SYSTEM"`) — Jackson serialises enums by name. We don't import
// {@code ChatRole} from `@vance/generated` here because it is generated
// as a *numeric* enum, which makes Vue's runtime prop-type check
// expect a Number and warn on every incoming string. Treat the role
// as a plain string at the component boundary instead.
type RoleName = 'USER' | 'ASSISTANT' | 'SYSTEM';

/** ASK_USER picker option (mirrors the {@code label/description} schema
 *  defined in {@code ArthurActionSchema} / {@code EddieActionSchema}).
 *  Kept as a re-export so existing call-sites stay valid; the new
 *  canonical name is {@link QuestionOption} in QuestionCanvas. */
export type AskUserOption = QuestionOption;

const props = withDefaults(defineProps<{
  role: RoleName | string;
  content: string;
  /** ISO string or epoch-millis number — both rendered as relative/local. */
  createdAt?: string | number | Date;
  /** True if the bubble is still streaming (no canonical message yet). */
  streaming?: boolean;
  /**
   * True for sub-process (worker) chat echoes — recipes spawned by the
   * main chat (e.g. {@code rezept-suche}). Renders compact, green, and
   * truncated to {@link #lineMaxChars} so the worker chatter doesn't
   * compete with the main thread for visual weight. Mirrors the foot
   * client's {@code worker()} channel.
   */
  worker?: boolean;
  /** Optional sub-process name shown as a prefix in worker mode. */
  processName?: string;
  /** Max characters for worker truncation (0 = disabled). Defaults to
   *  the env-configured {@code uiTheme.lineMaxChars}. */
  lineMaxChars?: number;
  /**
   * Optional structured metadata mirroring
   * {@code ChatMessageDto.meta}. Today we only consume
   * {@code askUserOptions}; future keys (typed side-channels) are
   * ignored gracefully.
   */
  meta?: Record<string, unknown>;
  /**
   * When the meta carries picker options, this flag controls whether
   * the buttons are still actionable. Set false once the user has
   * answered (a later USER message landed) so stale buttons grey out
   * instead of double-firing the same answer.
   */
  optionsActionable?: boolean;
}>(), {
  worker: false,
  lineMaxChars: () => uiTheme.lineMaxChars,
  optionsActionable: true,
});

const emit = defineEmits<{
  (e: 'pickOption', label: string): void;
}>();

const askUserOptions = computed<AskUserOption[]>(() => {
  const raw = props.meta?.['askUserOptions'];
  if (!Array.isArray(raw)) return [];
  const out: AskUserOption[] = [];
  for (const item of raw) {
    if (!item || typeof item !== 'object') continue;
    const obj = item as Record<string, unknown>;
    const label = obj['label'];
    if (typeof label !== 'string' || !label.trim()) continue;
    const desc = obj['description'];
    out.push({
      label: label.trim(),
      description: typeof desc === 'string' && desc.trim() ? desc.trim() : undefined,
    });
  }
  return out;
});

/**
 * Engine-action type from {@code meta.actionType}. Drives the
 * render-mode dispatch — see spec §11. Absent on USER messages,
 * fallback-text replies (LLM emitted raw text instead of an
 * arthur_action / eddie_action tool call), and legacy messages
 * persisted before the actionType tagging landed.
 */
const actionType = computed<string | null>(() => {
  const v = props.meta?.['actionType'];
  return typeof v === 'string' && v.trim() ? v.trim().toUpperCase() : null;
});

const isAskUser = computed(() =>
  actionType.value === ACTION_TYPE_ASK_USER || askUserOptions.value.length > 0,
);
const isReject = computed(() => actionType.value === ACTION_TYPE_REJECT);
const isWait   = computed(() => actionType.value === ACTION_TYPE_WAIT);

function onPick(label: string): void {
  if (!props.optionsActionable) return;
  emit('pickOption', label);
}

const isUser = computed(() => props.role === 'USER');
const isAssistant = computed(() => props.role === 'ASSISTANT');
const isSystem = computed(() => props.role === 'SYSTEM');

/**
 * True when the message contains rich-content artifacts (fenced code
 * blocks with a kind tag, or {@code vance:} Markdown links). Such
 * messages get a full-width bubble so the {@code <KindBox>} canvas
 * (mindmap, table, graph, PDF preview, …) is readable rather than
 * squeezed into the chat's default {@code max-w-[85%]}. See
 * specification/inline-and-embedded-content.md §11.6.
 */
const hasRichContent = computed<boolean>(() => {
  const src = props.content;
  if (!src) return false;
  // Fenced block with non-empty lang tag (the kind discriminator).
  if (/^ {0,3}```[A-Za-z][\w-]*/m.test(src)) return true;
  // Markdown link or image with vance: URI.
  if (/!?\[[^\]]*\]\(vance:/.test(src)) return true;
  return false;
});

const workerText = computed<string>(() => {
  if (!props.worker) return '';
  const max = props.lineMaxChars;
  // Collapse newlines so a long multi-line worker reply stays one
  // visual row — the user only needs the gist; full content is in
  // the engine's own log if they want detail.
  const flat = props.content.replace(/\s+/g, ' ').trim();
  if (max <= 0 || flat.length <= max) return flat;
  return flat.slice(0, Math.max(0, max - 3)) + '...';
});

const formatted = computed<string>(() => {
  if (!props.createdAt) return '';
  const d = props.createdAt instanceof Date ? props.createdAt : new Date(props.createdAt);
  if (isNaN(d.getTime())) return '';
  return d.toLocaleTimeString();
});

// Inline-style overrides from env. Resolved at module load (Vite
// inlines `import.meta.env` at build time), so these don't need to
// be reactive.
const workerStyle = computed(() => paletteStyle(uiTheme.worker));
const userStyle = computed(() => paletteStyle(uiTheme.user));
const assistantStyle = computed(() => paletteStyle(uiTheme.assistant));
const systemStyle = computed(() => paletteStyle(uiTheme.system));

const bubbleStyle = computed(() => {
  if (isUser.value) return userStyle.value;
  if (isAssistant.value) return assistantStyle.value;
  if (isSystem.value) return systemStyle.value;
  return null;
});
</script>

<template>
  <!-- Worker-channel echo: compact one-liner, no markdown render.
       Default colour is DaisyUI's `text-success`; an env-defined fg
       override (`VITE_VANCE_COLOR_WORKER`) wins via inline style. -->
  <div v-if="worker" class="flex justify-start">
    <div
      class="max-w-[85%] text-xs truncate flex items-center gap-2"
      :class="workerStyle ? '' : 'text-success/80'"
      :style="workerStyle ?? undefined"
    >
      <span class="font-mono opacity-70">[{{ processName ?? '?' }} · {{ String(role).toLowerCase() }}]</span>
      <span class="truncate">{{ workerText }}</span>
      <span v-if="streaming" class="inline-block w-1.5 h-1.5 rounded-full bg-success animate-pulse shrink-0" />
    </div>
  </div>

  <div
    v-else
    class="flex"
    :class="isUser ? 'justify-end' : 'justify-start'"
  >
    <div
      class="rounded-2xl px-4 py-2.5 shadow-sm"
      :class="[
        hasRichContent ? 'w-full' : 'max-w-[85%]',
        bubbleStyle ? '' : (isUser ? 'bg-primary text-primary-content' : ''),
        bubbleStyle ? '' : (isAssistant ? 'bg-base-100 border border-base-300' : ''),
        bubbleStyle ? '' : (isSystem ? 'bg-base-200 text-sm italic opacity-80' : ''),
      ]"
      :style="bubbleStyle ?? undefined"
    >
      <div
        v-if="!isUser"
        class="text-xs opacity-60 mb-1 flex items-center gap-2"
      >
        <span>{{ String(role).toLowerCase() }}</span>
        <span v-if="streaming" class="inline-block w-1.5 h-1.5 rounded-full bg-success animate-pulse" />
        <span v-if="formatted" class="opacity-60">· {{ formatted }}</span>
      </div>
      <!-- ASK_USER question canvas — question text + structured option
           buttons as one closed unit. See spec §11 (meta.actionType
           dispatch). Falls back to legacy showOptions check so old
           messages without actionType still render correctly. -->
      <QuestionCanvas
        v-if="isAskUser"
        :content="content"
        :options="askUserOptions"
        :actionable="optionsActionable"
        @pick="onPick"
      />
      <!-- WAIT — async work in flight; show only a thin status line, no
           full bubble payload. -->
      <div v-else-if="isWait" class="text-xs italic opacity-70">
        <span class="inline-block w-1.5 h-1.5 rounded-full bg-warning animate-pulse mr-2" />
        {{ content }}
      </div>
      <!-- REJECT — out-of-scope refusal; render in muted/warning tone. -->
      <div v-else-if="isReject" class="text-sm italic opacity-80">
        <MarkdownView :source="content" />
      </div>
      <!-- ANSWER / RELAY / untagged: default Markdown rendering. -->
      <MarkdownView v-else :source="content" />
    </div>
  </div>
</template>

// client/packages/vance-fingers/src/screens/chat/components/MessageBubble.tsx
import { useMemo } from 'react';
import { Pressable, Text, View } from 'react-native';
import { ChatRole } from '@vance/generated';

/**
 * Structured ASK_USER picker entry. Mirrors the schema set by the
 * action handlers in {@code ArthurActionSchema} / {@code
 * EddieActionSchema}. The Markdown rendering of the same data sits
 * in {@link Props.content} as a fallback for clients that don't
 * implement the picker.
 */
export interface AskUserOption {
  label: string;
  description?: string;
}

interface Props {
  role: ChatRole;
  content: string;
  /** Stream-buffered messages render with a slight visual cue. */
  streaming?: boolean;
  /**
   * Optional structured metadata mirroring {@code ChatMessageDto.meta}.
   * Today we only consume {@code askUserOptions}; unknown keys are
   * ignored gracefully.
   */
  meta?: Record<string, unknown> | null;
  /**
   * Whether the picker buttons are still clickable. Set false once
   * the user has answered (a later USER message landed) so stale
   * buttons grey out instead of double-firing the same answer.
   */
  optionsActionable?: boolean;
  /**
   * Picker click handler — receives the option {@code label}. The
   * caller feeds it into the chat send path so a click is
   * semantically identical to typing the same text.
   */
  onPickOption?: (label: string) => void;
}

/**
 * Single chat bubble. User messages right-aligned in the primary
 * colour, assistant messages left-aligned with a neutral surface,
 * system messages full-width with muted styling.
 *
 * <p>When an assistant message carries {@code meta.askUserOptions},
 * the picker renders below the text — see
 * {@code specification/eddie-engine.md} §5.6 / §5.8.
 */
export function MessageBubble({
  role,
  content,
  streaming = false,
  meta,
  optionsActionable = true,
  onPickOption,
}: Props) {
  const options = useMemo<AskUserOption[]>(() => {
    const raw = meta?.['askUserOptions'];
    if (!Array.isArray(raw)) return [];
    const out: AskUserOption[] = [];
    for (const item of raw) {
      if (!item || typeof item !== 'object') continue;
      const obj = item as Record<string, unknown>;
      const label = obj['label'];
      if (typeof label !== 'string' || !label.trim()) continue;
      const desc = obj['description'];
      out.push({
        label: label.trim(),
        description:
          typeof desc === 'string' && desc.trim() ? desc.trim() : undefined,
      });
    }
    return out;
  }, [meta]);

  if (role === ChatRole.SYSTEM) {
    return (
      <View className="px-4 py-1">
        <Text className="text-xs italic text-slate-500 dark:text-slate-400 text-center">
          {content}
        </Text>
      </View>
    );
  }
  const isUser = role === ChatRole.USER;
  return (
    <View className={`px-3 py-1 ${isUser ? 'items-end' : 'items-start'}`}>
      <View
        className={`max-w-[85%] rounded-2xl px-3 py-2 ${
          isUser
            ? 'bg-blue-600'
            : streaming
              ? 'bg-slate-100 dark:bg-slate-800 opacity-80'
              : 'bg-slate-100 dark:bg-slate-800'
        }`}
      >
        <Text
          className={`text-base ${
            isUser ? 'text-white' : 'text-slate-900 dark:text-slate-100'
          }`}
        >
          {content}
        </Text>
        {options.length > 0 ? (
          <View className="mt-3 flex-row flex-wrap gap-2">
            {options.map((opt) => (
              <Pressable
                key={opt.label}
                onPress={() => {
                  if (!optionsActionable) return;
                  onPickOption?.(opt.label);
                }}
                disabled={!optionsActionable}
                className={`px-3 py-1.5 rounded-lg border ${
                  optionsActionable
                    ? 'border-blue-500/40 bg-blue-500/10 active:bg-blue-500/20'
                    : 'border-slate-300 dark:border-slate-600 bg-slate-200/40 dark:bg-slate-700/40 opacity-50'
                }`}
              >
                <Text
                  className={`text-sm font-medium ${
                    optionsActionable
                      ? 'text-blue-700 dark:text-blue-200'
                      : 'text-slate-500 dark:text-slate-400'
                  }`}
                >
                  {opt.label}
                </Text>
                {opt.description ? (
                  <Text
                    className={`text-[10px] mt-0.5 ${
                      optionsActionable
                        ? 'text-blue-700/70 dark:text-blue-200/70'
                        : 'text-slate-500/70 dark:text-slate-400/70'
                    }`}
                  >
                    {opt.description}
                  </Text>
                ) : null}
              </Pressable>
            ))}
          </View>
        ) : null}
      </View>
    </View>
  );
}
