// client/packages/vance-face/src/components/VEmptyState.vue
<script setup lang="ts">
interface Props {
  headline: string;
  body?: string;
}

defineProps<Props>();
</script>

<template>
  <div class="flex flex-col items-center justify-center text-center py-12 gap-3">
    <div v-if="$slots.icon" class="text-4xl opacity-60">
      <slot name="icon" />
    </div>
    <h3 class="text-lg font-semibold">{{ headline }}</h3>
    <p v-if="body" class="text-sm opacity-70 max-w-md">{{ body }}</p>
    <div v-if="$slots.action" class="mt-2">
      <slot name="action" />
    </div>
  </div>
</template>

// client/packages/vance-fingers/src/components/VEmptyState.tsx
import { Text, View } from 'react-native';

interface Props {
  headline: string;
  body?: string;
  icon?: React.ReactNode;
  action?: React.ReactNode;
}

/**
 * Consistent "nothing here" panel for any list-style screen.
 * Centred vertically inside the parent.
 */
export function VEmptyState({ headline, body, icon, action }: Props) {
  return (
    <View className="flex-1 items-center justify-center px-8 gap-3">
      {icon ? <View>{icon}</View> : null}
      <Text className="text-lg font-semibold text-slate-900 dark:text-slate-100 text-center">
        {headline}
      </Text>
      {body ? (
        <Text className="text-sm text-slate-600 dark:text-slate-400 text-center">{body}</Text>
      ) : null}
      {action ? <View className="mt-2">{action}</View> : null}
    </View>
  );
}
