// client/packages/vance-face/src/chat/PlanModeIndicator.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import type { TodoItem } from '@vance/generated';

// ProcessMode and TodoStatus arrive on the wire as Java enum *names*
// (Jackson default). The generated TS enums are numeric, so importing
// them and comparing with `===` against the wire value would always
// miss. Treat both as string-literal types at the boundary — same
// pattern as MessageBubble's RoleName / ProgressFeed's Kind.
type ProcessModeName = 'NORMAL' | 'EXPLORING' | 'PLANNING' | 'EXECUTING';
type TodoStatusName = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED';

const props = defineProps<{
  mode: ProcessModeName;
  todos: TodoItem[];
  planMeta: { version: number; summary?: string } | null;
}>();

const { t } = useI18n();

const showPending = computed(() => props.mode === 'PLANNING' && props.planMeta !== null);
const showTodos = computed(() => props.todos.length > 0);
const visible = computed(() => showPending.value || showTodos.value);

const planTitle = computed<string>(() => {
  const v = props.planMeta?.version ?? 1;
  return v > 1
    ? t('chat.planMode.planTitleVersioned', { version: v })
    : t('chat.planMode.planTitle');
});

function statusOf(item: TodoItem): TodoStatusName {
  return (item.status as unknown as TodoStatusName) ?? 'PENDING';
}

function markerOf(item: TodoItem): string {
  switch (statusOf(item)) {
    case 'IN_PROGRESS': return '[~]';
    case 'COMPLETED': return '[✓]';
    case 'PENDING':
    default: return '[ ]';
  }
}

function labelOf(item: TodoItem): string {
  if (statusOf(item) === 'IN_PROGRESS' && item.activeForm && item.activeForm.trim()) {
    return item.activeForm;
  }
  return item.content;
}

function rowClassOf(item: TodoItem): string {
  switch (statusOf(item)) {
    case 'IN_PROGRESS': return 'text-warning font-medium';
    case 'COMPLETED': return 'opacity-50 line-through';
    case 'PENDING':
    default: return '';
  }
}
</script>

<template>
  <div
    v-if="visible"
    class="border-t border-base-300 bg-base-200/60 px-6 py-3 flex flex-col gap-3"
  >
    <div
      v-if="showPending"
      class="rounded-lg border border-info/40 bg-info/10 px-3 py-2 text-sm flex flex-col gap-1"
    >
      <div class="flex items-center gap-2">
        <span class="font-semibold text-info">{{ planTitle }}</span>
        <span class="text-xs uppercase tracking-wide opacity-60">
          {{ $t('chat.planMode.awaitingApproval') }}
        </span>
      </div>
      <div v-if="planMeta?.summary" class="text-xs opacity-80 break-words">
        {{ planMeta.summary }}
      </div>
      <div class="text-xs opacity-60">
        {{ $t('chat.planMode.approvalHint') }}
      </div>
    </div>

    <div v-if="showTodos" class="text-xs">
      <div class="uppercase tracking-wide opacity-60 font-semibold mb-1.5">
        {{ $t('chat.planMode.todosTitle') }}
      </div>
      <ul class="flex flex-col gap-0.5 font-mono">
        <li
          v-for="item in todos"
          :key="item.id || item.content"
          :class="rowClassOf(item)"
        >
          <span>{{ markerOf(item) }}</span>
          <span class="ml-2">{{ labelOf(item) }}</span>
        </li>
      </ul>
    </div>
  </div>
</template>

// client/packages/vance-mobile/src/screens/chat/components/PlanModeIndicator.tsx
import { Text, View } from 'react-native';
import { ProcessMode, TodoStatus, type TodoItem } from '@vance/generated';
import { normalizeEnum } from '@/util/enum';
import type { PlanMeta } from '@/hooks/useChatLive';

interface Props {
  mode: ProcessMode;
  todos: TodoItem[];
  planMeta: PlanMeta | null;
}

/**
 * Persistent Plan-Mode panel for the mobile chat. Mirrors the web
 * variant: a pending-plan banner while {@code mode === PLANNING} plus
 * a TodoList that stays visible across PLANNING and EXECUTING. Hides
 * itself when there is nothing to show — the parent screen does not
 * need to gate it.
 */
export function PlanModeIndicator({ mode, todos, planMeta }: Props) {
  const showPending = mode === ProcessMode.PLANNING && planMeta !== null;
  const showTodos = todos.length > 0;
  if (!showPending && !showTodos) return null;

  return (
    <View className="px-4 py-3 border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900">
      {showPending ? <PendingPlanCard meta={planMeta!} /> : null}
      {showTodos ? <TodoList items={todos} pendingPlanAbove={showPending} /> : null}
    </View>
  );
}

function PendingPlanCard({ meta }: { meta: PlanMeta }) {
  const title = meta.version > 1 ? `Plan v${meta.version}` : 'Plan';
  return (
    <View className="rounded-lg border border-blue-300 dark:border-blue-700 bg-blue-50 dark:bg-blue-900/30 px-3 py-2">
      <View className="flex-row items-center gap-2">
        <Text className="text-sm font-semibold text-blue-700 dark:text-blue-200">{title}</Text>
        <Text className="text-[10px] uppercase tracking-wide text-blue-700/70 dark:text-blue-200/70">
          wartet auf Freigabe
        </Text>
      </View>
      {meta.summary ? (
        <Text className="mt-1 text-xs text-slate-700 dark:text-slate-300">{meta.summary}</Text>
      ) : null}
      <Text className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
        Antworte mit „ok"/„mach so" für Freigabe oder mit Korrekturen.
      </Text>
    </View>
  );
}

function TodoList({ items, pendingPlanAbove }: { items: TodoItem[]; pendingPlanAbove: boolean }) {
  return (
    <View className={pendingPlanAbove ? 'mt-3' : ''}>
      <Text className="text-[10px] uppercase tracking-wide text-slate-500 dark:text-slate-400 font-semibold mb-1.5">
        Plan-Schritte
      </Text>
      <View className="gap-0.5">
        {items.map((item) => (
          <TodoRow key={item.id || item.content} item={item} />
        ))}
      </View>
    </View>
  );
}

function TodoRow({ item }: { item: TodoItem }) {
  const status = normalizeEnum(TodoStatus, item.status);
  const marker =
    status === TodoStatus.IN_PROGRESS ? '[~]'
      : status === TodoStatus.COMPLETED ? '[✓]'
        : '[ ]';
  const label =
    status === TodoStatus.IN_PROGRESS && item.activeForm && item.activeForm.trim().length > 0
      ? item.activeForm
      : item.content;
  const textCls =
    status === TodoStatus.IN_PROGRESS
      ? 'text-amber-700 dark:text-amber-300 font-semibold'
      : status === TodoStatus.COMPLETED
        ? 'text-slate-400 dark:text-slate-500 line-through'
        : 'text-slate-700 dark:text-slate-200';
  return (
    <View className="flex-row">
      <Text className={`text-xs font-mono ${textCls}`}>{marker}</Text>
      <Text className={`ml-2 text-xs flex-1 ${textCls}`}>{label}</Text>
    </View>
  );
}
